### ISSUE TITLE
Questions: License. Guzzle 6 Support.

### ISSUE THREAD

**Issue by stevenscg** [jippi/vault-php-sdk#1]
Thanks for sharing! This looks great.

Have you considered attaching a license to this project? I'd love to use it in some of my projects as long as the license is compatible (MIT ideally).

Do you have any interest in upgrading to Guzzle 6? I saw your PR on the consul PHP SDK project. I did something myself similar on a fork of that project.

**Comment by jippi** [comment]
@stevenscg I consider it MIT, just forgot to mention it anywhere :) 

Upgrading to Guzzle 6 would be fine by me, can you PR it ? for Consul-SDK it was quite simple

**Comment by stevenscg** [comment]
Sounds good. I'll work on the PR. Just wanted first to check since some projects either need or want to stay on Guzzle 5 for various reasons.

**Comment by stevenscg** [comment]
@jippi For the Guzzle 6 upgrade, do you have a personal preference for the changes in `Client.php`?

The [Consul PHP SDK](https://github.com/sensiolabs/consul-php-sdk/pull/19/files) replaced `send` with `doRequest`.

I [upgraded](https://github.com/stevenscg/consul-php-sdk/commit/4661a66c9c00bd7353f12b99de119a1915128ed6) my fork a few months earlier, but left the `send` method in place and public and switched `createRequest` to `Request` using the Psr RequestInterface.
