### ISSUE TITLE
Error :  Using $this when not in object context

### ISSUE THREAD

**Issue by Harshivsd12345** [jippi/vault-php-sdk#6]
Fatal error: Uncaught Error: Using $this when not in object context in E:\XAMPP\htdocs\vault_example\examples\shell.php:220 Stack trace: #0 E:\XAMPP\htdocs\vault_example\examples\shell.php(362): App\Shell\VaultShell::create() #1 {main} thrown in E:\XAMPP\htdocs\vault_example\examples\shell.php on line 220

**Comment by jippi** [comment]
please provide usage pattern and code
